title: Title
author: znet12345678
email: znet12345678@gmail.com
theme: minima
description: > # this means to ignore newlines until "baseurl:"
  This is for a class assignment

# social links
github_username:  znet12345678 # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
